# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Grifnas.OrizontRSS
PackageVersion: 1.6.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: Orizont.exe
  PortableCommandAlias: orizont-rss
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/grifnas/OrizontRSS/releases/download/v1.6.1/Orizont-RSS-1.6.1-win-x64.zip
  InstallerSha256: EBE60BA4C8BC1FAB4109F957C430FF13783CCB1B09B36FF23697FD325485B34C
ManifestType: installer
ManifestVersion: 1.10.0
